### ISSUE TITLE
Won't show up in game activity 

### ISSUE THREAD

**Issue by SeveralP** [Pizzabelly/EasyRP#145]
![image_2020-12-18_133705](https://user-images.githubusercontent.com/66889083/102648777-1ddd1680-4136-11eb-982b-e4e3f7dd6275.png)

Any help? Client id is correct

**Comment by bhavyagosai** [comment]
This is how it exactly looks like when it works tho...
Maybe your png reference might have some error or typo

**Comment by SeveralP** [comment]
> This is how it exactly looks like when it works tho...
> Maybe your png reference might have some error or typo

This is my config
`[Identifiers]
ClientID=789551523792683098

[State]
State=Real: 45.87.29.114
Details=Vpn: 241.110.249.241
StartTimestamp=1608315387
EndTimestamp=

[Images]
LargeImage=large
LargeImageTooltip=
SmallImage=
SmallImageTooltip=`

**Comment by bhavyagosai** [comment]
Well it's not wrong...
The name of the largeimage is correct according to the name of png you uploaded online right?
I don't seem to see any other problem because even if your client ID was wrong you wouldn't get an output as 
"Displaying presence for ...."
Therefore everything seems to work fine... Idk why it isn't displaying...

**Comment by SeveralP** [comment]
> Well it's not wrong...
> The name of the largeimage is correct according to the name of png you uploaded online right?
> I don't seem to see any other problem because even if your client ID was wrong you wouldn't get an output as
> "Displaying presence for ...."
> Therefore everything seems to work fine... Idk why it isn't displaying...

Ah I figured it out, apparently, there has to be a space before the id
