### ISSUE TITLE
A New War

### ISSUE THREAD

**Issue by GeorgeCY2** [Pizzabelly/EasyRP#23]
so i had this program for months, and had no issue to it, all i had to do is exclude it everything and for anyone else works perfectly like me, hit the thumbs up button and of not you can hit that dislike, impretty sure that *around* 40% of people hasn't got issues with the program
and now let's get into the part:
my discord friend volcanicer was testing the program, he experienced problems but his files was fine thank goodness, he also has a good strong pc and malwarebytes as his antivirus, malwarebytes and Kaspersky is the best antivirus, and it will trigger whenever it is or not, idk why my friend's one kept having weird things, for me i had no issues as i said
and after that test we are going to have a *github discord war I*
so i want you to to tell the truth and hit the thumbs up if you had any issues in the start you had the program and hit the thumbs down if not, we are talking about a new war on what it is true or not, alright let's let it begin!

**Comment by volcanicer** [comment]
I don't think a "war" over the matter of weather or not this program is malicious is appropriate. I believe we should settle this in a friendly way. I'm currently doing some testing with the version I downloaded here (the .zip) and so far I have had a bit of an issue, however upon further investigation it turns out something else on my PC was doing something weird. I would like to request the .exe file from anyone here. Have it? DM me on Discord please: **volcanicer#1122**.

**Comment by GeorgeCY2** [comment]
alright, let's hire you as a king then

**Comment by GeorgeCY2** [comment]
closing it, see #22 , thanks to @volcanicer

**Comment by Pizzabelly** [comment]
Wow, @GeorgeCY2 thanks for having my back LOL. I haven't checked this repo in a while (clearly) but I noticed all "virus" issues and I couldn't figure out why. But yeah thanks for helping me out :)

**Comment by GeorgeCY2** [comment]
ik this might be late, but no problem @Pizzabelly :) tho you should also thank to @volcanicer which he did the `investigation` job and helped me :D
